const baseURL = "/api/"
export default{
    // 用户登录接口
    USERLOGIN:baseURL+"userlogin",
    //菜单管理接口
    MENULIST:baseURL+"menulist",
    MENUADD:baseURL+"menuadd",
    MENUINFO:baseURL+"menuinfo",
    MENUEDIT:baseURL+"menuedit",
    MENUDELETE:baseURL+"menudelete",
    //角色管理接口
    ROLELIST:baseURL+"rolelist",
    ROLEADD:baseURL+"roleadd",
    ROLEINFO:baseURL+"roleinfo",
    ROLEEDIT:baseURL+"roleedit",
    ROLEDELETE:baseURL+"roledelete",
    //管理员管理接口
    USERLIST:baseURL+"userlist",
    USERADD:baseURL+"useradd",
    USERCOUNT:baseURL+"usercount",
    USERINFO:baseURL+"userinfo",
    USEREDIT:baseURL+"useredit",
    USERDELETE:baseURL+"userdelete",
    //商品分类管理接口
    CATELIST:baseURL+"catelist",
    CATEADD:baseURL+"cateadd",
    CATEINFO:baseURL+"cateinfo",
    CATEEDIT:baseURL+"cateedit",
    CATEDELETE:baseURL+"catedelete",
    //商品规格管理接口
    SPECSLIST:baseURL+"specslist",
    SPECSADD:baseURL+"specsadd",
    SPECSCOUNT:baseURL+"specscount",
    SPECSINFO:baseURL+"specsinfo",
    SPECSEDIT:baseURL+"specsedit",
    SPECSDELETE:baseURL+"specsdelete",
    //商品管理
    GOODSLIST:baseURL+"goodslist",
    GOODSADD:baseURL+"goodsadd",
    GOODSCOUNT:baseURL+"goodscount",
    GOODSINFO:baseURL+"goodsinfo",
    GOODSEDIT:baseURL+"goodsedit",
    GOODSDELETE:baseURL+"goodsdelete",
    //会员管理
    MEMBERLIST:baseURL+"memberlist",
    MEMBERINFO:baseURL+"memberinfo",
    MEMBEREDIT:baseURL+"memberedit",
    MEMBERCOUNT:baseURL+"membercount",
    //轮播图接口
    BANNERLIST:baseURL+"bannerlist",
    BANNERADD:baseURL+"banneradd",
    BANNERINFO:baseURL+"bannerinfo",
    BANNEREDIT:baseURL+"banneredit",
    BANNERDELETE:baseURL+"bannerdelete",
    //限时秒杀管理
    SECKADD:baseURL+"seckadd",
    SECKLIST:baseURL+"secklist",
    SECKINFO:baseURL+"seckinfo",
    SECKEDIT:baseURL+"seckedit",
    SECKDELETE:baseURL+"seckdelete",
}